services:
  # Render.com bepul rejasida hamma narsani 1 ta xizmat ichida ishga tushirish uchun
  - type: web
    name: water-backend
    runtime: node
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: COURIER_BOT_TOKEN
        sync: false
      - key: CUSTOMER_BOT_TOKEN
        sync: false
      - key: PUBLIC_URL
        sync: false
