services:
  # Render.com bepul rejasida hamma narsani 1 ta xizmat ichida ishga tushirish uchun
  - type: web
    name: water-backend
    runtime: node
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_6fF7SLygGoHt@ep-nameless-bread-ayi58quk-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        value: water_super_secret_key_123!
      - key: COURIER_BOT_TOKEN
        value: 8641929454:AAFXvYRmp8xpdFQyG-jZ3hObXzdr7TuqAnY
      - key: CUSTOMER_BOT_TOKEN
        value: 8696687383:AAEDnnQZ06JXmBYrYUMZme6-5zbxarxTD04
      - key: PUBLIC_URL
        value: https://water-backend-hymh.onrender.com
